
- name: Download WSO2 sp
  get_url:
    url: "https://github.com/wso2/product-sp/releases/download/v{{ sp_version }}/wso2sp-{{ sp_version }}.zip"
    dest: "{{ home_dir }}downloads/wso2sp-{{ sp_version }}.zip"
    checksum: md5:1e6e1f881e9740399231e3e3765d4535
    remote_src: yes

- name: Extract WSO2 sp
  unarchive:
    src: "{{ home_dir }}downloads/wso2sp-{{ sp_version }}.zip"
    creates: "{{ home_dir }}products/wso2sp-{{ sp_version }}"
    dest: "{{ home_dir }}products"
    remote_src: yes
