- name: Check if the version already exists on the remote system.
  stat:
    path: "{{ is_home }}"
  register: version_deployed

- name: Add wso2is symlink to /usr/local/bin.
  file:
    src: "{{ is_home }}/bin/wso2server.sh"
    dest: "/usr/local/bin/{{ wso2_app }}"
    state: link
    mode: 0755
  when: not version_deployed.stat.exists

- name: Add wso2 app init script.
  template:
    src: wso2.service.j2
    dest: "/etc/systemd/system/{{ wso2_app }}.service"
    mode: 0755
  notify: reload systemd
  tags:
   - systemd


#- name: Ensure wso2-app is set to start on boot.
#  become: true
#  become_method: sudo
#  service:
#    name: "{{ wso2_app }}"
#    enabled: yes
#    state: started
#  notify: restart wso2-app

- name: Ensure wso2-app is set to start on boot.
  systemd:
    name: "{{ wso2_app }}"
    enabled: yes
    state: started
    masked: no
  notify: reload systemd
  tags:
   - systemd

#- name : Appy templates for configuration
#  import_tasks: wso2is-config-main.yml
#  notify: restart wso2-app
#    - config
