---
# handlers file for wso2-is
- name: restart wso2-app
  systemd:
    name: "{{ wso2_app }}"
    state: restarted
- name: reload systemd
  systemd:
    name: "{{ wso2_app }}"
    daemon_reload: yes
